### ISSUE TITLE
Implement custom component spec for each component

### ISSUE THREAD

**Issue by PhilippeMoussalli** [ml6team/fondant#174]
### Problem Statement
_[Describe the problem or need that the feature aims to address. Provide background information and any relevant context.]_

Reusable components are currently associated with one component specs defining what the component accepts and what it produces. While this might make sense for transform components since they do accept and produce a specific input and output, it is not the case for the Data reader and writer component which can produce varying subsets and fields. 

### Proposed Approach
_[Explain the high-level approach you plan to take to implement this feature. ]_

In order to tackle this issue, the user needs to be able to define custom component specs for Reader and Writer components (e.g. `load_from_hub` and `write_to_hub`). Currently, the component specs is harcoded within a components inside the docker image which is passed to the component as part of the build process. 

```python
component = CaptionImagesComponent.from_file(../fondant_component.yaml)
```
this makes it difficult to modify for different use cases. It needs to be passed dynamically as part of a component argument during the pipeline definition to the `Component` class. 

```python
component_spec = ComponentSpec(specificiation=<specification as a component argument dict>)
component = CaptionImagesComponent(spec=component_spec)
```

This can be done by adding the component spec as an additional required input to the component arguments and passing it to the component during the pipeline definition [similar to the metadata and manifest](https://github.com/ml6team/fondant/blob/e54544dcf98601093a197eb357e66432a88398ad/fondant/pipeline.py#L321). 

The last issue that remains to be solved is the fact that we need to parse the arguments prior to defining the `Component` to extract the `component_spec` dict. We can implement an additional `classmethod` for the `Component` class to initialize it from the arguments. This would requires changing the `_add_and_parse_args()` to a class method. 

```python
class Component(ABC):
    """Abstract base class for a Fondant component."""

    def __init__(self, spec: ComponentSpec) -> None:
        self.spec = spec
        self.args = self._add_and_parse_args()

    @classmethod
    def from_file(
        cls, path: t.Union[str, Path] = "../fondant_component.yaml"
    ) -> "Component":
        """Create a component from a component spec file.

        Args:
            path: Path to the component spec file
        """
        component_spec = ComponentSpec.from_file(path)
        return cls(component_spec)

    @classmethod
    def from_args(cls) -> "Component":
        """Create a component from a component spec file.

        Args:
            path: Path to the component spec file
        """
        component_spec = cls._add_and_parse_args()['component_spec']
        return cls(component_spec)
```

### Implementation Steps/Tasks
_[List the specific tasks or subtasks involved in implementing the feature. The tasks can be broken down into additional tickets]_

```[tasklist]
### Tasks
- [x] Change pipeline class and component specs class to accept a `component_spec` as an argument
- [x] Add a class method the `Component` class to enable initializing it from an argument
- [x] Update reusable components to use the new component definition
```

### Potential Impact
_[Identify and describe the aspects of the repository that may be affected by the feature implementation. This may include codebase  dependencies (manifest, component spec, component class, pipeline class, schema...), reusable components,  or any other relevant parts of the codebase]_

This change will only need to be implemented for the Read/Write components. However, since we do not have a way of distinguishing which is which in the pipeline, all components will now be defined with the `from_args` instead of the `from_file` method. All the current existing components need to be updated. 

We can remove the line from the Dockerfile where we copy the component specs.

### Testing
_[Outline the testing strategy for the implemented feature. Describe the different test cases that should be considered to ensure the feature works as expected. Specify the expected outcomes for each test case.]_

Test initializing components with the custom component spec with the `from_args` methods and check similar to [this](https://github.com/ml6team/fondant/blob/e54544dcf98601093a197eb357e66432a88398ad/tests/test_component.py#LL44C1-L44C1)

### Documentation
_[Explain how the new feature will be documented. Specify the files or sections that need to be updated to provide clear instructions on using the feature. Consider updating the README file, inline code comments, or any other relevant documentation.]_

Update the [custom component docs](https://github.com/ml6team/fondant/blob/main/docs/custom_component.md) with a description on how to implement a custom component. 

### Feedback and Suggestions
_[Encourage others to provide feedback or suggestions on the proposed feature implementation. This can promote collaboration and help refine the approach before proceeding.]_

### Dependent features
_[Specify if the implementation of this feature is dependent on another feature or functionality within the repository. Describe the nature of the dependency and provide any necessary context for understanding its impact on the current feature implementation.]_

Dependent on the DataWriter feature #138. Not a hard dependency but easier to validate if this feature is implemented beforehand. 

### Additional Notes
_[Add any additional notes, suggestions, or considerations that are relevant to the feature implementation but haven't been covered in the previous sections.]_

We might need to remove the `.from_file()` method altogether if it's no longer used.

**Comment by RobbeSneyders** [comment]
Thanks for the clear description of the issue @PhilippeMoussalli!

Maybe we can take another approach as well:

The user can define the Read/WriteComponent as a custom component only containing the component spec:
```
|- components/
   |- custom_load_component
      |- fondant_component.yaml
pipeline.py
```

The `fondant_component.yaml` just needs to refer to the general image and define its custom `consumes` / `produces`:
```yaml
name: CustomLoadComponent
description: Custom component that loads a specific dataset from the hub
image: ghcr.io/ml6team/load_from_hf_hub:latest  # General image

produces:  # Custom produces
  images:
    fields:
      data:
        type: binary
      width:
        type: int16
      height:
        type: int16
  captions:
    fields:
      data:
        type: string

args:  # Inherited
  dataset_name:
    description: Name of dataset on the hub
    type: str
```

In the pipeline, the user can then include the component as follows:
```python
from fondant.pipeline import ComponentOp

my_load_component = ComponentOp(
    component_spec_path="components/CustomLoadComponent/fondant_component.yaml"
)
```

I think this should already be possible with the current implementation and feels a bit like "subclassing" the component.

Am I missing something why this would not work?

**Comment by PhilippeMoussalli** [comment]
This could work but the `fondant_component.yaml` needs to be also consumed by the component during run time ([link](https://github.com/ml6team/fondant/blob/271a53e7e9799d00f6700fd3a9f62de3b602033e/components/load_from_hf_hub/src/main.py#L70)). We're currently copying it during the build process. ([link](https://github.com/ml6team/fondant/blob/271a53e7e9799d00f6700fd3a9f62de3b602033e/components/load_from_hf_hub/Dockerfile#L17)).  

This means that you would have to rebuild your image everytime you want to produce different subsets/fields which is not optimal. I proposed passing the specs as a pipeline argument to avoid rebuilding everytime.

**Comment by PhilippeMoussalli** [comment]
Nice! I think that should do it
