### ISSUE TITLE
Allow handling of nested data types

### ISSUE THREAD

**Issue by PhilippeMoussalli** [ml6team/fondant#178]
### Problem Statement

Fondant currently supports handling pyarrow data types as specified in the [schema](https://github.com/ml6team/fondant/blob/main/fondant/schema.py). However, sometimes there is a need to specify nested data types as a list/array. We have a [quick implementation](https://github.com/ml6team/fondant/blob/43567274fc00c87c96011ec0dc3c18931d54e10a/fondant/schema.py#LL54C1-L55C1) on how this is done but it's not a permanent solution since it is not nicely defined, requires a lot of replication and is only limited to nested function of 1 layer. The solution should ideally be able to handle any of the pyarrow types defined in the schema while also allow for creating nested data types that can span multiple layers deep. 

The [swagger array data type](https://swagger.io/docs/specification/data-models/data-types/#:~:text=the%20null%20value.-,Arrays,-Arrays%20are%20defined) can serve as an inspiration for this solutions where nested data types are defined as follows: 

One layer
```yaml
type: array
items:
  type: string
```

Two layers
```yaml
type: array
items:
  type: array
  items:
    type: integer
```

Currently, fondant implements a similar schema but the `array` type is not supported (only pyarrow types):

```yaml
consumes:
  images:
    fields:
      url:
        type: string
```

We need to change the schema to accept nested types similar to how Swagger does it: 

```yaml
consumes:
  embeddings:
    fields:
      url:
        type: array
        items:
          type: integer
```

### Implementation Steps/Tasks

- [x] Change the `common.json` [file](https://github.com/ml6team/fondant/blob/main/fondant/schemas/common.json) to allow fields of handling nested data types. 
- [x] Change the `Field` class in [`schema.py`](https://github.com/ml6team/fondant/blob/main/fondant/schema.py) where `type` attribute should be able to handle different nested types. 
We also might want to adjust the [`Type`](https://github.com/ml6team/fondant/blob/43567274fc00c87c96011ec0dc3c18931d54e10a/fondant/schema.py#L13) class and create a nested data type constructor method for a `list` or `array`:
```python
from schema import Type
Type.list[Type.string] # pa.list_(pa.int8())
```
- [x] Possible required changes to the `Manifest` and `ComponentSpec`
- [x] Make necessary change to affected components (embedding, segmentation)
- [x] Remove `int8_list` and `float32_list` from `schema.py`

### Potential Impact

Users will have to be more careful when defining data types and it has to be properly documented

### Testing

Create dummy component specs with nested data types and check their attributes access similar to [this](https://github.com/ml6team/fondant/blob/43567274fc00c87c96011ec0dc3c18931d54e10a/tests/test_component_specs.py#LL46C1-L47C1)

### Documentation

Update [`component_spec.md`](https://github.com/ml6team/fondant/blob/main/docs/component_spec.md)
### Dependent features

Related to https://github.com/orgs/ml6team/projects/1/views/1?pane=issue&itemId=29567255
