### ISSUE TITLE
Support default values for component arguments

### ISSUE THREAD

**Issue by PhilippeMoussalli** [ml6team/fondant#179]
### Problem Statement

Some components have many arguments associated with them. It is not always necessary for the end-user to define all of them and we might want to stick with default values. Currently this is not available and all the components require an argument. 

This feature should enable users to set default values for certain components while defining the components. Those values can then be optionally passed during the pipeline definition.

We first define the default arguments at the `component_spec` level: 

_compnent_spec.yaml_
```yaml
name:component
description: Component that downloads images based on URLs
image: ghcr.io/ml6team/download_images:latest

consumes:
   ...

produces:
  ...

args:
  min_image_size: #mandatory argument
    description: Minimum size of the images.
    type: int
  timeout: #optional argument
    description: Maximum time (in seconds) to wait when trying to download an image 
    default: 3
    type: int
```

Then, at the step when we add and parse the arguments in  [`component.py`](https://github.com/ml6team/fondant/blob/43567274fc00c87c96011ec0dc3c18931d54e10a/fondant/component.py#L104)
we check if a default argument is provided, if so we set the optional field when adding the argument: 

```python

    def _add_and_parse_args(self):
        parser = argparse.ArgumentParser()
        component_arguments = self._get_component_arguments()

        for arg in component_arguments.values():
            # Input manifest is not required for loading component
            if arg.name == "input_manifest_path":
                input_required = False
            else:
                input_required = True
           
            if arg.default is not None:
               default = arg.default
            else: 
               default = None
            parser.add_argument(
                f"--{arg.name}",
                type=kubeflow2python_type[arg.type],
                required=input_required,
                default=default,
                help=arg.description,
            )

        return parser.parse_args()
```

Additionally, we need to make the necessary changes to the `component_spec.py` by adding an optional `default` field to the [`Argument`](https://github.com/ml6team/fondant/blob/43567274fc00c87c96011ec0dc3c18931d54e10a/fondant/component_spec.py#L41) dataclass as well as modifying the [`KubeflowComponentSpec`](https://github.com/ml6team/fondant/blob/43567274fc00c87c96011ec0dc3c18931d54e10a/fondant/component_spec.py#L195) as specified [here](https://www.kubeflow.org/docs/components/pipelines/v1/reference/component-spec/#:~:text=the%20input%20arguments.-,Example%20of%20a%20component%20specification,-A%20component%20specification) to include default arguments. 
 
### Implementation Steps/Tasks

- [ ] Change the [`component_spec.json`](https://github.com/ml6team/fondant/blob/43567274fc00c87c96011ec0dc3c18931d54e10a/fondant/schemas/component_spec.json#L62) to accept an optional `default` field
- [ ] Make necessary change to the argument parser in  [`component.py`](https://github.com/ml6team/fondant/blob/43567274fc00c87c96011ec0dc3c18931d54e10a/fondant/component.py#L104)
- [ ] Make necessary changes to the [`component_spec.py`](https://github.com/ml6team/fondant/blob/43567274fc00c87c96011ec0dc3c18931d54e10a/fondant/component_spec.py)

### Testing

Create a component with optional argument and test whether omitting the argument will return the default values. Also test if we can override the default values successfully.

Additional testing will have to be done when running kubeflow but difficult to test with tests (has to be done manually with a mock submitted pipeline).  

### Documentation
Extend the `Args` [documentation](https://github.com/ml6team/fondant/blob/main/docs/component_spec.md#:~:text=a%20better%20understanding.-,Args,-The%20args%20section) with examples of default pipelines.

### Dependent features

None
