### ISSUE TITLE
Refactor KFP (pipelines.py) into Compiler and Runner

### ISSUE THREAD

**Issue by GeorgesLorre** [ml6team/fondant#270]
```[tasklist]
### Tasks
- [ ] Create Kubeflow compiler
- [ ] Abstract intercomponent dependecy checker into basecompiler
- [ ] Create Kubeflow runner
- [ ] Refactor pipelines.py to be more abstract
- [ ] Expand CLI interface with kubeflow
- [ ] Update examples
```

**Comment by GeorgesLorre** [comment]
@PhilippeMoussalli I tried to group some of the task you created into 1 big issue with subtasks which are closely related

**Comment by PhilippeMoussalli** [comment]
Thanks! I don't think there is anything left out. After that, we could maybe tackle partial execution
