### ISSUE TITLE
Add component tests

### ISSUE THREAD

**Issue by RobbeSneyders** [ml6team/fondant#301]
Our reusable components should be tested at least for every release.

**Comment by satishjasthi** [comment]
@RobbeSneyders, Shall I take up this issue and add test cases for all existing components

**Comment by mrchtr** [comment]
# Problem Statement

Currently, there are no component tests for the reusable components, which can lead to the incorporation of unexpected
behavior into reusable components during a release.

To avoid this, we should add component tests that can be executed before each release.

Furthermore, by establishing a well-defined component test strategy, we can expedite the development process of
individual components.

The process of adding component tests will be documented to ensure clarity and consistency in the testing procedures.

# Proposed Approach

To ensure consistency across tests, I would propose adding an `AbstractComponentTest` or a `TestExecutor` class.
This shared utility will offer a common way to initialise/execute a component test.

During each test, we can focus on testing the transform method (the core business logic) of a single component.

By utilising this shared testing class, new tests for different components can be implemented more efficiently.

## Parameterize Test definition by using json fixtures

To simplify the process even more, we could define a default test case structure based on a
parameterized fixture. This approach will enable users to add JSON files for their test configurations, specifying the
expected input, output dataframe, and component arguments.

A `TestExecuter` could initialize the parameterized tests using the
JSON files, executing each test case automatically.

As a user, you will only need to provide the necessary JSON files with the required configurations for your tests. The
testing framework will take care of initializing the tests and comparing the actual output with the expected output for
each test case.

E.g.

```json
{
  "user_arguments": {
    "model_name": "..."
  },
  "input_data": <expected input dataframe>,
  "expected_output": <expected output dataframe>
}
```

Testing different components becomes straightforward and more accessible to users, reducing
the effort required to set up and execute tests for individual components.

This setup can probably not be used for complexer components.

## Run component test in the release pipeline

Since each component may have specific testing requirements, we may need to modify the component's Dockerfile to adapt
it to the officially [proposed way](https://docs.docker.com/language/java/run-tests/) of running tests.
This will help ensure that the testing environment aligns with the specific needs of each component's test suite.

```Dockerfile
FROM --platform=linux/amd64 python:3.8-slim as base

RUN apt-get update && \
...

FROM base as tests
COPY tests/ tests/
RUN ["python", "-m", "pytest", "tests/"]

FROM base
WORKDIR /component/src
ENTRYPOINT ["python", "main.py"]
```

This implementation would be downwards compatible and allows to continue building and running the components using the
current approach. 
Execution of test can be achieved by running docker build --target tests ., and if we subsequently build an image directly after, the cached docker layers will be utilised.

Potential downside is that the test execution and the image build will be executed within the same CI/CD step.

# Implementation Steps/Task

- [x] Implement `AbstractComponentTest` and/or `TestExecuter` (already addressed by: @satishjasthi in #311)
- [ ] Implement fixture-based test case
- [ ] Implement a test case for each component
- [ ] Modify release pipeline to execute the component tests
- [ ] Update documentation regarding creating new components

**Comment by satishjasthi** [comment]
@mrchtr I would love to take up these list of tasks to create a generalised test executor for reusable components

**Comment by satishjasthi** [comment]
@mrchtr, I have updated codebase with parameterised json fixture, please review. Furthermore, is it required to create a separate TestExecutor class here because when we run test cases using pytest it will automatically collect the test cases and run them.

**Comment by mrchtr** [comment]
Thanks @satishjasthi! I will take a look at your branch.
You are right - pytest will discover new test cases automatically. The main difference between the `AbstractComponentTest` and `TestExecuter` is primarily the name. When the idea came up, we wanted to name it TestExecuter first. 

Is it ok for you to wait with the implementation of the next steps, until we get some feedback from @RobbeSneyders on the proposal? Maybe I missed some details.

**Comment by satishjasthi** [comment]
Ya Sure, we can. Please let me know once you have discussed with @RobbeSneyders

**Comment by RobbeSneyders** [comment]
Thanks for the detailed proposal @mrchtr!

> To ensure consistency across tests, I would propose adding an AbstractComponentTest or a TestExecutor class.
This shared utility will offer a common way to initialise/execute a component test.

This sounds good to me, @satishjasthi's implementation in #311 looks clean!

Do note that this will only work for the `PandasTransformComponent`, so we probably need a separate testing class for each abstract component class.

---

> Parameterize Test definition by using json fixtures

Maybe I'm missing something, but I'm not seeing that much benefit in using json fixtures, since the implementation in #311 is already minimalistic. I do see some issues, like it being very hard to define the input and expected data in json format.

Can't we parametrize the test class instead?

---

The multi-stage docker image looks like a neat approach. Not sure what you mean with

> Potential downside is that the test execution and the image build will be executed within the same CI/CD step.

but you can execute the stages separately by providing a `target` stage to the `build` command, and [docker will only build that stage and the ones it depends on](https://docs.docker.com/build/building/multi-stage/#differences-between-legacy-builder-and-buildkit) (when using BuildKit, which we do).

**Comment by mrchtr** [comment]
Thanks for the review @RobbeSneyders! 


> To ensure consistency across tests, I would propose adding an AbstractComponentTest or a TestExecutor class.
This shared utility will offer a common way to initialise/execute a component test.

Naively, I assumed we could check what specific type of input is being used by a component, either pandas or dask dataframes. If we are dealing with a dask dataframe, we could convert the pandas dataframe to a dask one, no?

> Parameterize Test definition by using json fixtures
>> Can't we parametrize the test class instead?

Yes should work. Just thought about to have a easy manageable straight forward way to initialise component test. Cause we got a good blueprint for implementing test now, we just have to find a way to define easy and minimalistic the data to run the test on. See your point that json files might not the best approach here.  

>> Not sure what you mean with:
> Potential downside is that the test execution and the image build will be executed within the same CI/CD step.

True, BuildKit does the magic. Shouldn't be an issue.

**Comment by RobbeSneyders** [comment]
> Naively, I assumed we could check what specific type of input is being used by a component, either pandas or dask dataframes. If we are dealing with a dask dataframe, we could convert the pandas dataframe to a dask one, no?

When using Dask dataframes, all the methods of the `ComponentTest` should accept and return Dask dataframes, so it requires a different implementation by the user. The assertion logic is probably also different as Dask dataframes are lazily evaluated, so we either need to compare their metadata or compute them. I would keep it explicit and not start converting between Pandas and Dask implicitly.

**Comment by satishjasthi** [comment]
@mrchtr , As discussed on Discord, Should I use create independent test cases for each of the component rather than using the abstract test class?

**Comment by mrchtr** [comment]
@satishjasthi exactly. I have had a discussion with @RobbeSneyders about this topic. It might be not the best idea to hide the test utils inside of fondant. Rather each test should be self explaining.

**Comment by RobbeSneyders** [comment]
Closing this, as we have the testing mechanism in place. Would still be great to add tests to more components though.
