### ISSUE TITLE
Enable partial pipeline execution for local runner

### ISSUE THREAD

**Issue by PhilippeMoussalli** [ml6team/fondant#313]
Issue discussed in more details [here](https://github.com/ml6team/fondant/pull/292)

```[tasklist]
### Tasks
- [ ] https://github.com/ml6team/fondant/issues/314
- [ ] https://github.com/ml6team/fondant/issues/315
- [ ] https://github.com/ml6team/fondant/issues/321
- [ ] https://github.com/ml6team/fondant/issues/317
```
