### ISSUE TITLE
Run KfP v2 pipeline on cluster

### ISSUE THREAD

**Issue by RobbeSneyders** [ml6team/fondant#494]
Validate that our KfP v2 pipelines run on a new KfP v2 cluster and fix issues we encounter along the way.

```[tasklist]
### Tasks
- [ ] #418 
- [ ] https://github.com/ml6team/fondant/issues/486
- [ ] https://github.com/ml6team/fondant/issues/421
- [ ] https://github.com/ml6team/fondant/issues/505
- [ ] https://github.com/ml6team/fondant/issues/506
```

**Comment by RobbeSneyders** [comment]
Done in #477
