### ISSUE TITLE
Infer when a subset or the index needs to be written to a new location

### ISSUE THREAD

**Issue by RobbeSneyders** [ml6team/fondant#55]
https://github.com/ml6team/fondant/issues/42 provides functionality to generate the output manifest from the input manifest and component spec. But it does not yet correctly update the location of the subsets or location. It should deduce when this is necessary and update the location with the new one.

Based on our offline discussion:
- A component should define any data it changes in its `output_subsets`. So a subset needs to be written to a new location if and only if it is defined in the component `output_subsets`. Since we only need the component specification, this can be done statically.
- To know if the index changes, we need to check if the input index and output index of a component at runtime. We need to check how we can do this efficiently using Dask. As a first step we will always rewrite the index and implement this check as optimization later.

Based on this, we get the following subtasks:

```[tasklist]
### Tasks
- [x] Update manifest evolution to include subset location updates (#56)
- [x] Implement always writing the index to a new location (#56)
- [ ] https://github.com/ml6team/fondant/issues/70
```

**Comment by NielsRogge** [comment]
@RobbeSneyders the `evolve` method should also include updating the metadata of the manifest (based on args.metadata)

**Comment by RobbeSneyders** [comment]
Yes they should be indeed. I'm not sure when the `run_id` and `component_id` will become available though. They might only be available at runtime.

**Comment by NielsRogge** [comment]
The run_id is only available at run time, but the component_id is just the name of the component, which is also present in the component spec. (`FondantComponentSpec`).

**Comment by RobbeSneyders** [comment]
Shouldn't the `component_id` also contain the version of the component (eg. the commit hash?) Unless this would be completely captured by the `run_id`.

**Comment by NielsRogge** [comment]
Previously, the Manifest had a separate `commit_hash` key included in its metadata, besides the `run_id`, `component_name`.
