### ISSUE TITLE
Improve availability of useful components

### ISSUE THREAD

**Issue by RobbeSneyders** [ml6team/fondant#561]
The components that we offer should be highly reusable to maximize their value compared to their effort.

```[tasklist]
### Tasks
- [ ] #502
- [ ] https://github.com/ml6team/fondant-use-cases/issues/31
- [ ] #562
- [ ] Select and implement some very generic components, potentially LLM based
- [ ] https://github.com/ml6team/fondant/issues/576
- [ ] https://github.com/ml6team/fondant/issues/569
```
