### ISSUE TITLE
Make it easier to create custom components

### ISSUE THREAD

**Issue by RobbeSneyders** [ml6team/fondant#563]
```[tasklist]
### Tasks
- [ ] #331
- [ ] https://github.com/ml6team/fondant/issues/565
- [ ] https://github.com/ml6team/fondant/issues/558
- [ ] https://github.com/ml6team/fondant/issues/560
- [ ] https://github.com/ml6team/fondant/issues/192
- [ ] https://github.com/ml6team/fondant/issues/570
- [ ] https://github.com/ml6team/fondant/issues/568
- [ ] https://github.com/ml6team/fondant/issues/578
- [ ] https://github.com/ml6team/fondant/issues/580
- [ ] https://github.com/ml6team/fondant/issues/585
```

**Comment by RobbeSneyders** [comment]
Closing due to too wide scope. We will track subtasks separately.
