### ISSUE TITLE
Simplify dataset format and interface

### ISSUE THREAD

**Issue by RobbeSneyders** [ml6team/fondant#564]
We should revisit the design of the subsets and fields before moving forward with the implementation of any other composability-related issues.

```[tasklist]
### Tasks
- [ ] https://github.com/ml6team/fondant/issues/567
- [ ] https://github.com/ml6team/fondant/issues/652
- [ ] https://github.com/ml6team/fondant/issues/655
- [ ] https://github.com/ml6team/fondant/issues/656
- [ ] https://github.com/ml6team/fondant/issues/642
- [ ] https://github.com/ml6team/fondant/issues/639
- [ ] https://github.com/ml6team/fondant/issues/640
- [ ] #244
- [ ] https://github.com/ml6team/fondant/issues/180
- [ ] https://github.com/ml6team/fondant/issues/649
```

**Comment by PhilippeMoussalli** [comment]
@RobbeSneyders should #244 and #180 be put on hold until we finish revisiting the subset and field design?

**Comment by RobbeSneyders** [comment]
Yes, I would do so.

**Comment by RobbeSneyders** [comment]
I moved everything related to the pipeline interface to #643. The documentation for both the dataset format (this issue) and the pipeline interface (#643) are bundled there.
