### ISSUE TITLE
Expand data loaders/writers

### ISSUE THREAD

**Issue by PhilippeMoussalli** [ml6team/fondant#569]
Current data loaders/writers are limited, it would be ideal to expand them further, this would first require identifying the most valuable sources/sink that can be implemented based on internal/external feedback and then implement them 
```[tasklist]
### Tasks
- [ ] https://github.com/ml6team/fondant/issues/581
- [ ] https://github.com/ml6team/fondant/issues/582
- [ ] https://github.com/ml6team/fondant/issues/583
- [ ] https://github.com/ml6team/fondant/issues/584
```
