### ISSUE TITLE
Update README & documentation with user journey in mind

### ISSUE THREAD

**Issue by RobbeSneyders** [ml6team/fondant#572]
```[tasklist]
### Tasks
- [ ] https://github.com/ml6team/fondant/issues/605
- [ ] https://github.com/ml6team/fondant/issues/601
- [ ] https://github.com/ml6team/fondant/issues/610
- [ ] https://github.com/ml6team/fondant/issues/602
- [ ] https://github.com/ml6team/fondant/issues/600
- [ ] https://github.com/ml6team/fondant/issues/603
- [ ] https://github.com/ml6team/fondant/issues/604
- [ ] https://github.com/ml6team/fondant/issues/598
- [ ] https://github.com/ml6team/fondant/issues/599
- [ ] https://github.com/ml6team/fondant/issues/509
```

**Comment by PhilippeMoussalli** [comment]
I would start from a landing page that has a nice overview of the logical ordering of all the concepts that the users need to know. The ordering should: 
* Enable users to quickly start with a pipeline 
* Start from simple/essential concepts and buildup towards more complex ones

Proposal on how this landing page could look like: 

### Getting started with Fondant 
_The goal here is to get the user started with Fondant quickly by showcasing how to get started and showcasing some implemented example pipelines. Going through this section should be as frictionless as possible and complex concepts should be delayed._

- Introduction (links to page explaining what fondant is, problems it's trying to solve, roadmap, getting involved) 
- Installing Fondant (docker + pip) 
- Running your first pipeline (Links to [notebook](https://github.com/ml6team/fondant-use-cases/issues/41)
- Example pipelines (showcase current existing example pipelines, ...) 
- FAQ (clears doubts about Fondant, go 
- Get support (github issues and discord) 


### Fondant fundamentals 

### Supported Runners 

### Internals 
Now that the users understand know how to get started, understand the fundamentals and runners, they can take a deep dive into how Fondant is built  and advanced complex related to integration with other frameworks (Dask, partition, ...). Other concepts and internals can be explained such as caching, manifest, how streaming work, dashboard, performance

**Comment by RobbeSneyders** [comment]
We should document both the CLI & SDK for usage from a notebok.

**Comment by RobbeSneyders** [comment]
Thanks @PhilippeMoussalli.

I wouldn't work with a single landing page though, but structure our whole documentation with these ideas in mind. Iterating on your proposal, I would propose the following structure:

- Introduction (= readme)
- Getting started
  - Installation
  - Running an existing pipeline with local runner
  - Exploring the results
- Components
  - Using reusable components
  - Using generic components
  - Creating custom components
- Runners
  - Local runner
  - Vertex Runner
  - KfP runner
- Advanced
  - Architecture

Instead of having a separate API reference, I would integrate the relevant snippets as part of the documentation pages ([see the new connexion documentation as an example](https://connexion.readthedocs.io/en/latest/quickstart.html#)).

**Comment by PhilippeMoussalli** [comment]
> Thanks @PhilippeMoussalli.
> 
> I wouldn't work with a single landing page though, but structure our whole documentation with these ideas in mind. Iterating on your proposal, I would propose the following structure:
> 
> * Introduction (= readme)
> * Getting started
>   
>   * Installation
>   * Running an existing pipeline with local runner
>   * Exploring the results
> * Components
>   
>   * Using reusable components
>   * Using generic components
>   * Creating custom components
> * Runners
>   
>   * Local runner
>   * Vertex Runner
>   * KfP runner
> * Advanced
>   
>   * Architecture
> 
> Instead of having a separate API reference, I would integrate the relevant snippets as part of the documentation pages ([see the new connexion documentation as an example](https://connexion.readthedocs.io/en/latest/quickstart.html#)).

Yes that seems logical. We could maybe have an additional page as a guide to the documentation similar to Beam https://beam.apache.org/documentation/. Can be after the introduction

**Comment by PhilippeMoussalli** [comment]
- [ ] https://github.com/ml6team/fondant/issues/598
- [ ] https://github.com/ml6team/fondant/issues/599
- [ ] https://github.com/ml6team/fondant/issues/600
- [ ] https://github.com/ml6team/fondant/issues/601
- [ ] https://github.com/ml6team/fondant/issues/602
- [ ] https://github.com/ml6team/fondant/issues/603
- [ ] https://github.com/ml6team/fondant/issues/604
