### ISSUE TITLE
Write documentation

### ISSUE THREAD

**Issue by RobbeSneyders** [ml6team/fondant#60]
We should update the README and create the following detailed documentation pages:
```[tasklist]
### Tasks
- [ ] #63
- [ ] #61
- [ ] #62
- [ ] #64
- [ ] https://github.com/ml6team/fondant/issues/131
- [ ] https://github.com/ml6team/fondant/issues/132
- [ ] https://github.com/ml6team/fondant/issues/133
- [ ] https://github.com/ml6team/fondant/issues/134
- [ ] https://github.com/ml6team/fondant/issues/120
- [ ] https://github.com/ml6team/fondant/issues/121
```
