### ISSUE TITLE
Implement new pipeline interface

### ISSUE THREAD

**Issue by mrchtr** [ml6team/fondant#643]
Changes will effect the `pipeline` package. 

Implementation based on the discussion in #567 

Summarisation of 567, we will implement the following dataset interface: 

```
pipeline = Pipeline(
    pipeline_name="my_pipeline",
    pipeline_description="description of my pipeline",
    base_path="/foo/bar",
)

dataset = pipeline.read(
    name="load_images",
    schema={
        "image": type.binary  # or pa.binary()
    }
)

dataset = dataset.apply(
    name="caption_images", 
    consumes={
        "images_data": "image"
    }
    produces={
        "captions": "text"
    }


dataset = dataset.apply(
    component_dir="embed_text", 
    consumes={
        "text_data":"text"
    }
)

dataset.write(
    name="write_data", 
    schema={
        "image": "image", 
        "caption": "text" 
    }
)
```

```[tasklist]
### Tasks
- [ ] https://github.com/ml6team/fondant/issues/567
- [ ] https://github.com/ml6team/fondant/issues/688
- [ ] https://github.com/ml6team/fondant/issues/689
- [ ] https://github.com/ml6team/fondant/issues/638
- [ ] https://github.com/ml6team/fondant/issues/670
- [ ] https://github.com/ml6team/fondant-usecase-RAG/issues/12
- [ ] https://github.com/ml6team/fondant-usecase-controlnet/issues/4
- [ ] https://github.com/ml6team/fondant-usecase-filter-creative-commons/issues/5
```
