### ISSUE TITLE
Document lightweight python components

### ISSUE THREAD

**Issue by RobbeSneyders** [ml6team/fondant#799]
```[tasklist]
### Tasks
- [ ] https://github.com/ml6team/fondant/issues/807
- [ ] https://github.com/ml6team/fondant/issues/808
- [ ] https://github.com/ml6team/fondant/issues/809
- [ ] https://github.com/ml6team/fondant/issues/810
```

**Comment by PhilippeMoussalli** [comment]
```[tasklist]
### Tasks
- [ ] Update **getting started- Building your own pipeline**  to include python components (can include both custom-docker and custom-python based components),
- [ ] Update **getting started- Implementing custom components** on guide on how to implement a custom python component 
- [ ] Update **Components-Components** to include python based components 
- [ ]  Update **Components-Component spec** to include section on python based components explaining the equivalence to achieve the desired behavior 
- [ ] Update **Components-publishing components** to include information on how to publish python based components 
```
