### ISSUE TITLE
Add focus on writing output dataset

### ISSUE THREAD

**Issue by RobbeSneyders** [ml6team/fondant#823]
```[tasklist]
### Tasks
- [ ] https://github.com/ml6team/fondant/issues/824
- [ ] https://github.com/ml6team/fondant/issues/825
- [ ] https://github.com/ml6team/fondant/issues/836
```
