### ISSUE TITLE
Make Dataset the first class interface

### ISSUE THREAD

**Issue by GeorgesLorre** [ml6team/fondant#853]
Given our vision we want to promote the idea of a dataset. 

Now fondant is very pipeline focused where we see a pipeline as a graph of operations with intermediate datasets. We should rethink the our primary interface to enable the dataset first approach:

We should pack more functionality in the Dataset class:
- view data preview (html formatted like pandas)
- view data schema / metadata
- view lineage
- ...

We should abstract the Pipeline idea. Compiling and starting a pipeline is a cheap operation so it should be less static. If we store the correct information on the dataset class we can create pipelines from a dataset (and its dependencies).
```[tasklist]
### Tasks
- [ ] https://github.com/ml6team/fondant/issues/885
- [ ] https://github.com/ml6team/fondant/issues/886
- [ ] https://github.com/ml6team/fondant/issues/887
- [ ] https://github.com/ml6team/fondant/issues/900
- [ ] https://github.com/ml6team/fondant/issues/909
- [ ] https://github.com/ml6team/fondant/issues/910
- [ ] https://github.com/ml6team/fondant/issues/913
```
